version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - PARTICLE_ACCESS_TOKEN=${PARTICLE_ACCESS_TOKEN}
      - PARTICLE_DEVICE_ID=${PARTICLE_DEVICE_ID}
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
        - MONGO_INITDB_DATABASE=leds:27017
