version: '3.1'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/usr/src/app/src
    build:
      context: .
      args:
        - PAINTINLEDS_ENV
    environment:
      - PARTICLE_ACCESS_TOKEN
      - PARTICLE_DEVICE_ID
      - MONGO_INITDB_ROOT_PASSWORD
    depends_on:
      - db
  db:
    image: "${PAINTINLEDS_MONGO_IMAGE}"
    ports:
      - "27017:27017"
    volumes:
      - ~/db_volumes/paintinleds:/data/db
    environment:
        - MONGO_INITDB_DATABASE=leds
        - MONGO_INITDB_ROOT_USERNAME=prometheus
        - MONGO_INITDB_ROOT_PASSWORD
